### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by mekkablue** [mekkablue/Rimmer#1]
```
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 556, in processLayer_withArguments_
  File "plugin.py", line 106, in filter
  File "GlyphsApp/GlyphsApp/__init__.py", line 2182, in extend
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 517, in processFont_withArguments_
  File "plugin.py", line 106, in filter
  File "GlyphsApp/GlyphsApp/__init__.py", line 2182, in extend
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 556, in processLayer_withArguments_
  File "plugin.py", line 106, in filter
  File "GlyphsApp/GlyphsApp/__init__.py", line 2182, in extend
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 517, in processFont_withArguments_
  File "plugin.py", line 106, in filter
  File "GlyphsApp/GlyphsApp/__init__.py", line 2182, in extend
TypeError: 'NoneType' object is not iterable
```

**Comment by schriftgestalt** [comment]
It seems that this happens when the glyph is empty?

**Comment by mekkablue** [comment]
Yes, that was the problem. I think I fixed it.
